### ISSUE TITLE
New Changes: Gameplay

### ISSUE THREAD

**Issue by Azrielly** [Towoya/Elemix#11]
- Character Movement: Point and Click
   - Coding the algorithm
- No more compounding UI
   - Physical Compounding
- Slime Door/Obstacle: No more enemies
- Elements locked behind quizzes
- Level Saving
- Element Table Unlocking
- Level Progression

**Comment by Discord615** [comment]
Completed Scripts:
- Slime Doors
- Level Saving
- Element Lock
- Quiz

To Do:
- Level Complete Triggers

**Comment by Discord615** [comment]
Completed:
- Level Complete Triggers

**Comment by Discord615** [comment]
No Element Table Unlocking Yet:
- Unlocked after completing a quiz element lock.
  - Only if table unlocking is per element. This should not be the case if it's per category/family
- needs to be saved

**Comment by Towoya** [comment]
TO DO
- Player Interaction Range
- Multiple Obstacle in 1 Level

**Comment by Discord615** [comment]
> TO DO
> - Player Interaction Range
> - Multiple Obstacle in 1 Level
> - Increase Element Letter to 2 (For elements that have 2 letter symbol Ex. Chlorine (Cl) )

What obstacle? Is that just the quiz or something else?

**Comment by Towoya** [comment]
> > TO DO
> > 
> > * Player Interaction Range
> > * Multiple Obstacle in 1 Level
> > * Increase Element Letter to 2 (For elements that have 2 letter symbol Ex. Chlorine (Cl) )
> 
> What obstacle? Is that just the quiz or something else?

Multiple doors, since you have mention that when multiple doors are used, all of them have the same call function and would open all doors when they created the right mixture

**Comment by Discord615** [comment]
> > > TO DO
> > > 
> > > * Player Interaction Range
> > > * Multiple Obstacle in 1 Level
> > > * Increase Element Letter to 2 (For elements that have 2 letter symbol Ex. Chlorine (Cl) )
> > 
> > What obstacle? Is that just the quiz or something else?
> 
> Multiple doors, since you have mention that when multiple doors are used, all of them have the same call function and would open all doors when they created the right mixture

![20241005_134731.jpg](https://github.com/user-attachments/assets/7f5d2882-8e4a-4bd2-abee-860c3c953257)

Here's the flowchart of the door. This should allow us to have multiple doors for each level

**Comment by Discord615** [comment]
Completed:
- The ability to have multiple doors in a single level is now possible. Along with that, it is now possible to have multiple compounding panels and buttons for each door to use.
 - Note: Each compounding panel needs to have the compoundingPanel tag.

**Comment by Discord615** [comment]
Completed:
- Interact Distance
- Multiple Letters for elementLetter

**Comment by Discord615** [comment]
Few Reminders:
- Don't forget to set each compounding panel's tag to CompoundingPanel
  - This tag helps the code search for the compounding panels within the level
- Don't forget to set the element block's letter.
  - Due to the change of the letters from char to string, some letters have become numbers.
- Increase the interact distance in the inspector under the maincompounding manager

**Comment by Discord615** [comment]
To Fix:
- Implement score decrease if compounding fails

**Comment by Discord615** [comment]
> To Fix:
> 
> * Implement score decrease if compounding fails

Implemented. I will be closing this issue thread because it is starting to get bloated. Just create new issue thread if there are any new issues needed to be fixed
