### ISSUE TITLE
Changes in Specific Objectives

### ISSUE THREAD

**Issue by Towoya** [Towoya/Elemix#17]
This changes are still pending and would still be discussed with the programmer for it's feasibility

**Specific objective #2: To design a Scoring System that Reflects the Learning Outcomes of Grade 11 STEM Students at STI College Ortigas-Cainta in Understanding Elements and Chemical Mixtures.**

Proposed Changes:
Instead of relying to base the player's learning on how many stars they collected, we would now rely on how many quizzes they answer correctly which would then be interpreted as a percentage score at the end of each element family stage. 

The scoring system concept would be similar to the traditional school scoring system, The formula would be 50/50 = ((Ans) 50 ) + 50 = 100% assuming we have a total of 50 quizzes, 5 levels with 10 questions. We would also use the concept of the school's grading system where 75% would be the passing score. 

**Specific objective #3:  To develop a reward system to increase player engagement and motivation.**

Proposed Changes:

Short term reward: Rewarding with instant knowledge reward
Instead of traditional power-ups that helps the player in the game environment, knowledge based rewards would take its place. This rewards are in a form of facts, trivia, and additional information about certain elements. 

Long term reward: End of stage certificates/badge
Instead of complex achievements, this end-of-stage certificates/badges are acquired when a player reached the passing score of the stage, relating to Specific objective #2. So now, there would be a total of 10 certificates that the player could acquire since we have 10 element families. This certificates/badges would also be displayed in the main menu screen (If possible).

**Comment by Discord615** [comment]
Would this mean we are foregoing the scoring system of each level?

**Comment by Towoya** [comment]
> Would this mean we are foregoing the scoring system of each level?

that would still be applicable, they would not just be the source of basis on how we asses the player's gained knowledge. It would be more like "how good did they play that level"

**Comment by Discord615** [comment]
> > Would this mean we are foregoing the scoring system of each level?
> 
> that would still be applicable, they would just not be the source of basis on how we asses the player's gained knowledge. It would be more like "how good did they play that level"

Okay, but where would the score system be shown? Is it also per level or is it a group of levels?

**Comment by Towoya** [comment]
> > > Would this mean we are foregoing the scoring system of each level?
> > 
> > 
> > that would still be applicable, they would just not be the source of basis on how we asses the player's gained knowledge. It would be more like "how good did they play that level"
> 
> Okay, but where would the score system be shown? Is it also per level or is it a group of levels?

It would be at the end of the stage, Level 5. As each stage(Family element) would have 5 levels

**Comment by Discord615** [comment]
Can I get a more detailed explanation on how you would calculate the scoring?

**Comment by Towoya** [comment]
> Can I get a more detailed explanation on how you would calculate the scoring?

Example:
Reactive Non-Metals (Stage 1)
Level 1 - 10 Quizzes
Level 2 - 10 Quizzes
Level 3 - 10 Quizzes
Level 4 - 10 Quizzes
Level 5 - 10 Quizzes (At the end of this level, a scoreboard like panel or scene would show how many quizzes they got right)
Total: 50 Quizzes
50/50 = 1 * 50 = 50 + 50 = 100%

If a player lets say got 39 out of 50:
39/50 =  0.78 * 50 = 39 + 50 = 89%

**Comment by Discord615** [comment]
If I understand this correctly. This would mean that if the player did not get any pf the quizzes correct.. they still have 50%?

**Comment by Discord615** [comment]
I think we can just do it like this instead

50 (Score) / 50 (Overall Questions) = 1 * 100 = 100%

So if we use the example you have given

39/50 = 0.78 * 100 = 78%

**Comment by Discord615** [comment]
> > Can I get a more detailed explanation on how you would calculate the scoring?
> 
> Example:
> Reactive Non-Metals (Stage 1)
> Level 1 - 10 Quizzes
> Level 2 - 10 Quizzes
> Level 3 - 10 Quizzes
> Level 4 - 10 Quizzes
> Level 5 - 10 Quizzes (At the end of this level, a scoreboard like panel or scene would show how many quizzes they got right)
> Total: 50 Quizzes
> 50/50 = 1 * 50 = 50 + 50 = 100%
> 
> If a player lets say got 39 out of 50:
> 39/50 =  0.78 * 50 = 39 + 50 = 89%
> 

In regards to the panel, I will make it easy enough to get the final calculated score so you can handle the creation of the panel itself

**Comment by Discord615** [comment]
This has been completed
