### ISSUE TITLE
Found Bug: LevelManager no instance of object

### ISSUE THREAD

**Issue by Discord615** [Towoya/Elemix#30]
![image](https://github.com/user-attachments/assets/15968ded-3679-4170-bcd2-68886a72809b)
As seen above, there is an issue where, in line 150, starOutputs come as an empty object because switching scenes cause the LevelManager to lose the levelStarContainers.

Solution:
Possible fix is similar to the levelButtons.

**Comment by Towoya** [comment]
![Screenshot 2024-10-21 145054](https://github.com/user-attachments/assets/b14967de-aace-4e0f-b570-512a0f362aec)

might still have the same issue... this issue shows up when i click stage 1 from Category menu scene

**Comment by Discord615** [comment]
This has been fixed
