### ISSUE TITLE
Level Stats Saving Error

### ISSUE THREAD

**Issue by Towoya** [Towoya/Elemix#35]
![image](https://github.com/user-attachments/assets/f239fc80-3049-4f30-b40c-2956929fd72c)
![image](https://github.com/user-attachments/assets/9ac44f8e-5830-4fb6-88f5-35f8bf1589be)

Showing incorrect stars

**Comment by Discord615** [comment]
Pushed fix on this. Please Test it and close this issue if there are no more errors
